import os


def tenants(tenant_name):
    return {'8x8.com': {'etl_stack': 'etl-ms',
                        'gbm_db': 'gbm1_ms',
                        'gbm_stack': 'gbm1-ms',
                        'pod': 'pod1'},
            'alludo.com': {'etl_stack': 'etl-ms',
                           'gbm_db': 'gbm1_ms',
                           'gbm_stack': 'gbm1-ms',
                           'pod': 'pod3'},
            'arctiq.com': {'etl_stack': 'etl-ms',
                           'gbm_db': 'gbm1_ms',
                           'gbm_stack': 'gbm1-ms',
                           'pod': 'pod1'},
            'armis.com': {'etl_stack': 'etl-ms',
                          'gbm_db': 'gbm1_ms',
                          'gbm_stack': 'gbm1-ms',
                          'pod': 'pod1'},
            'aviso.com': {'etl_stack': 'etl-ms',
                          'gbm_db': 'gbm1_ms',
                          'gbm_stack': 'gbm1-ms',
                          'pod': 'pod2'},
            'bmc.com': {'etl_stack': 'etl-ms',
                        'gbm_db': 'gbm1_ms',
                        'gbm_stack': 'gbm1-ms',
                        'pod': 'pod4'},
            'bv.com': {'etl_stack': 'etl-ms',
                       'gbm_db': 'gbm1_ms',
                       'gbm_stack': 'gbm1-ms',
                       'pod': 'pod1'},
            'camunda.com': {'etl_stack': 'etl-ms',
                            'gbm_db': 'gbm1_ms',
                            'gbm_stack': 'gbm1-ms',
                            'pod': 'pod2'},
            'contractpodai.com': {'etl_stack': 'etl-ms',
                                  'gbm_db': 'gbm1_ms',
                                  'gbm_stack': 'gbm1-ms',
                                  'pod': 'pod5'},
            'conviva.com': {'etl_stack': 'etl-ms',
                            'gbm_db': 'gbm1_ms',
                            'gbm_stack': 'gbm1-ms',
                            'pod': 'pod2'},
            'data.ai': {'etl_stack': 'etl-ms',
                        'gbm_db': 'gbm1_ms',
                        'gbm_stack': 'gbm1-ms',
                        'pod': 'pod1'},
            'datadome.co': {'etl_stack': 'etl-ms',
                            'gbm_db': 'gbm1_ms',
                            'gbm_stack': 'gbm1-ms',
                            'pod': 'pod1'},
            'datastax.com': {'etl_stack': 'etl-ms',
                             'gbm_db': 'gbm1_ms',
                             'gbm_stack': 'gbm1-ms',
                             'pod': 'pod3'},
            'elastic.co': {'etl_stack': 'etl-ms',
                           'gbm_db': 'gbm1_ms',
                           'gbm_stack': 'gbm1-ms',
                           'pod': 'pod1'},
            'ezesoft.com': {'etl_stack': 'etl-ms',
                            'gbm_db': 'gbm1_ms',
                            'gbm_stack': 'gbm1-ms',
                            'pod': 'pod3'},
            'github.com': {'etl_stack': 'etl-ms',
                           'gbm_db': 'gbm1_ms',
                           'gbm_stack': 'gbm1-ms',
                           'pod': 'pod1'},
            'honeywell_gas.com': {'etl_stack': 'etl-ms',
                                  'gbm_db': 'gbm1_ms',
                                  'gbm_stack': 'gbm1-ms',
                                  'pod': 'pod1'},
            'honeywell_ppe.com': {'etl_stack': 'etl-ms',
                                  'gbm_db': 'gbm1_ms',
                                  'gbm_stack': 'gbm1-ms',
                                  'pod': 'pod2'},
            'honeywell_siot.com': {'etl_stack': 'etl-ms',
                                   'gbm_db': 'gbm1_ms',
                                   'gbm_stack': 'gbm1-ms',
                                   'pod': 'pod1'},
            'honeywell_sst.com': {'etl_stack': 'etl-ms',
                                  'gbm_db': 'gbm2_ms',
                                  'gbm_stack': 'gbm2-ms',
                                  'pod': 'pod1'},
            'ironclad.com': {'etl_stack': 'etl-ms',
                             'gbm_db': 'gbm1_ms',
                             'gbm_stack': 'gbm1-ms',
                             'pod': 'pod1'},
            'ivision.com': {'etl_stack': 'etl-ms',
                            'gbm_db': 'gbm1_ms',
                            'gbm_stack': 'gbm1-ms',
                            'pod': 'pod5'},
            'jfrog.com': {'etl_stack': 'etl-ms',
                          'gbm_db': 'gbm1_ms',
                          'gbm_stack': 'gbm1-ms',
                          'pod': 'pod3'},
            'launchdarkly.com': {'etl_stack': 'etl-ms',
                                 'gbm_db': 'gbm1_ms',
                                 'gbm_stack': 'gbm1-ms',
                                 'pod': 'pod3'},
            'lenovo.com': {'etl_stack': 'etl-ms',
                           'gbm_db': 'gbm1_ms',
                           'gbm_stack': 'gbm1-ms',
                           'pod': 'pod4'},
            'lumen.com': {'etl_stack': 'etl-ms',
                          'gbm_db': 'gbm2_ms',
                          'gbm_stack': 'gbm2-ms',
                          'pod': 'pod1'},
            'medius.com': {'etl_stack': 'etl-ms',
                           'gbm_db': 'gbm1_ms',
                           'gbm_stack': 'gbm1-ms',
                           'pod': 'pod3'},
            'movella.com': {'etl_stack': 'etl-ms',
                            'gbm_db': 'gbm2_ms',
                            'gbm_stack': 'gbm2-ms',
                            'pod': 'pod1'},
            'mural.co': {'etl_stack': 'etl-ms',
                         'gbm_db': 'gbm1_ms',
                         'gbm_stack': 'gbm1-ms',
                         'pod': 'pod2'},
            'netapp.com': {'etl_stack': 'etl-ms',
                           'gbm_db': 'gbm1_ms',
                           'gbm_stack': 'gbm1-ms',
                           'pod': 'pod2'},
            'newrelic.com': {'etl_stack': 'etl-ms',
                             'gbm_db': 'gbm1_ms',
                             'gbm_stack': 'gbm1-ms',
                             'pod': 'pod1'},
            'nextech.com': {'etl_stack': 'etl-ms',
                            'gbm_db': 'gbm1_ms',
                            'gbm_stack': 'gbm1-ms',
                            'pod': 'pod1'},
            'nuance.com': {'etl_stack': 'etl-ms',
                           'gbm_db': 'gbm1_ms',
                           'gbm_stack': 'gbm1-ms',
                           'pod': 'pod1'},
            'onetrust.com': {'etl_stack': 'etl-ms',
                             'gbm_db': 'gbm1_ms',
                             'gbm_stack': 'gbm1-ms',
                             'pod': 'pod5'},
            'processmap.com': {'etl_stack': 'etl-ms',
                               'gbm_db': 'gbm1_ms',
                               'gbm_stack': 'gbm1-ms',
                               'pod': 'pod1'},
            'redhelix.co.uk': {'etl_stack': 'etl-ms',
                               'gbm_db': 'gbm1_ms',
                               'gbm_stack': 'gbm1-ms',
                               'pod': 'pod2'},
            'redislabs.com': {'etl_stack': 'etl-ms',
                              'gbm_db': 'gbm1_ms',
                              'gbm_stack': 'gbm1-ms',
                              'pod': 'pod1'},
            'rescale.com': {'etl_stack': 'etl-ms',
                            'gbm_db': 'gbm1_ms',
                            'gbm_stack': 'gbm1-ms',
                            'pod': 'pod2'},
            'ringcentral.com': {'etl_stack': 'etl-ms',
                                'gbm_db': 'gbm1_ms',
                                'gbm_stack': 'gbm1-ms',
                                'pod': 'pod2'},
            'servicenow.com': {'etl_stack': 'etl-ms',
                               'gbm_db': 'gbm1_ms',
                               'gbm_stack': 'gbm1-ms',
                               'pod': 'pod1'},
            'silverpeak.com': {'etl_stack': 'etl-ms',
                               'gbm_db': 'gbm1_ms',
                               'gbm_stack': 'gbm1-ms',
                               'pod': 'pod1'},
            'singular.net': {'etl_stack': 'etl-ms',
                             'gbm_db': 'gbm1_ms',
                             'gbm_stack': 'gbm1-ms',
                             'pod': 'pod2'},
            'sourceday.com': {'etl_stack': 'etl-ms',
                              'gbm_db': 'gbm1_ms',
                              'gbm_stack': 'gbm1-ms',
                              'pod': 'pod3'},
            'ssc.com': {'etl_stack': 'etl-ms',
                        'gbm_db': 'gbm1_ms',
                        'gbm_stack': 'gbm1-ms',
                        'pod': 'pod3'},
            'ssi.com': {'etl_stack': 'etl-ms',
                        'gbm_db': 'gbm1_ms',
                        'gbm_stack': 'gbm1-ms',
                        'pod': 'pod1'},
            'ukg.com': {'etl_stack': 'etl-ms',
                        'gbm_db': 'gbm1_ms',
                        'gbm_stack': 'gbm1-ms',
                        'pod': 'pod2'},
            'vastdata.com': {'etl_stack': 'etl-ms',
                             'gbm_db': 'gbm1_ms',
                             'gbm_stack': 'gbm1-ms',
                             'pod': 'pod2'},
            'velocityglobal.com': {'etl_stack': 'etl-ms',
                                   'gbm_db': 'gbm1_ms',
                                   'gbm_stack': 'gbm1-ms',
                                   'pod': 'pod1'},
            'venafi.com': {'etl_stack': 'etl-ms',
                           'gbm_db': 'gbm1_ms',
                           'gbm_stack': 'gbm1-ms',
                           'pod': 'pod1'},
            'wiz.io': {'etl_stack': 'etl-ms',
                       'gbm_db': 'gbm1_ms',
                       'gbm_stack': 'gbm1-ms',
                       'pod': 'pod5'}}.get(tenant_name, {'etl_stack': 'etl-ms',
                                                         'gbm_stack': 'gbm1-ms',
                                                         'pod': 'pod1'})


def ms_connection_strings(pod):

    ## IMP-- This is not working , need to fix to get working GBM-MongoDB URL
    import os
    mongo_instance = {'pod1': 'db-microservice.aviso.com',
                      'pod2': 'db-microservice-pod2.aviso.com',
                      'pod3': 'db-microservice-pod3.aviso.com',
                      'pod4': 'db-microservice-pod4.aviso.com',
                      'pod5': 'db-microservice-pod5.aviso.com',
                      'stage': 'stagedb.aviso.com',
                      'dev': 'db-etl-qa.avisoaws.com'}.get(pod)
    username = os.environ['MONGO_USERNAME']
    if pod in ['pod1', 'pod2', 'pod3', 'pod4', 'pod5']:
        password = os.environ['MONGO_PASSWORD']
    else:
        password = os.environ['MONGO_PASSWORD_STAGE']
    return "mongodb://" + username + ":" + password + "@" + mongo_instance + ":27017/?authMechanism=DEFAULT&authSource=admin"


def fa_connection_strings(stack, tenant_name):
    import os
    from dotenv import load_dotenv
    load_dotenv()
     ## IMP-- This is not working , need to fix to get working GBM-MongoDB URL
    username = os.environ['MONGO_USERNAME']
    if stack == 'app':
        cluster = {'8x8.com': '2',
                   'alludo.com': '0',
                   'arctiq.com': '0',
                   'armis.com': '5',
                   'aviso.com': '0',
                   'bmc.com': '4',
                   'bv.com': '0',
                   'camunda.com': '2',
                   'contractpodai.com': '1',
                   'conviva.com': '0',
                   'data.ai': '2',
                   'datadome.co': '0',
                   'datastax.com': '5',
                   'elastic.co': '0',
                   'ezesoft.com': '4',
                   'github.com': '0',
                   'honeywell_gas.com': '2',
                   'honeywell_ppe.com': '1',
                   'honeywell_siot.com': '1',
                   'honeywell_sst.com': '4',
                   'ironclad.com': '5',
                   'ivision.com': '3',
                   'jfrog.com': '5',
                   'launchdarkly.com': '5',
                   'lenovo.com': '3',
                   'lumen.com': '2',
                   'medius.com': '5',
                   'movella.com': '0',
                   'mural.co': '2',
                   'netapp.com': '1',
                   'newrelic.com': '2',
                   'nextech.com': '3',
                   'nuance.com': '0',
                   'onetrust.com': '5',
                   'processmap.com': '3',
                   'redhelix.co.uk': '2',
                   'redislabs.com': '1',
                   'rescale.com': '3',
                   'ringcentral.com': '0',
                   'servicenow.com': '3',
                   'silverpeak.com': '3',
                   'singular.net': '0',
                   'sourceday.com': '3',
                   'ssc.com': '0',
                   'ssi.com': '3',
                   'ukg.com': '0',
                   'vastdata.com': '0',
                   'velocityglobal.com': '5',
                   'venafi.com': '2',
                   'wiz.io': '0'}.get(tenant_name, '3')
        mongo_instance = 'mongo-fmapp-prod-shard' + cluster + '-0.aviso.com'
        password = os.environ['MONGO_PASSWORD']
    elif stack == 'stage':
        mongo_instance = 'mongo-fmapp-stage-shard0-0.aviso.com'
        password = os.environ['MONGO_PASSWORD_STAGE']
    else:
        mongo_instance = 'mongo-fmapp-qa-shard0-0.aviso.com'
        password = os.environ['MONGO_PASSWORD']
    return "mongodb://" + username + ":" + password + "@" + mongo_instance + ":27016/?tls=true"



